name: vioo_app
description: A minimal Flutter app scaffold created by the assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0  # For OpenAI API calls
  tflite_flutter: ^0.11.0  # Local LLM fallback inference
  flutter_svg: ^2.2.1  # Render SVG assets such as the splash logo
  flutter_markdown: ^0.7.7+1  # Render formatted script output
  retry: ^3.1.2  # Retry utility for resilient HTTP calls
  hive: ^2.2.3  # Local persistence for generated assets
  hive_flutter: ^1.1.0  # Flutter bindings for Hive boxes
  google_sign_in: ^7.2.0  # Google Sign-In OAuth flow
  sign_in_with_apple: ^7.0.1  # Apple Sign-In support
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  firebase_auth_mocks: ^0.15.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/local_llm.tflite
    - assets/logo-vioo-white.svg
    - assets/logo-vioo-navy.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_vioo.png"
  min_sdk_android: 21
