name: vioo_app
description: A minimal Flutter app scaffold created by the assistant
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0  # For OpenAI API calls
  tflite_flutter: ^0.11.0  # Local LLM fallback inference
  flutter_svg: 2.0.7  # Render SVG assets such as the splash logo
  flutter_markdown: ^0.6.17  # Render formatted script output
  retry: ^3.1.2  # Retry utility for resilient HTTP calls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/local_llm.tflite
    - assets/logo-vioo-white.svg
    - assets/logo-vioo-navy.svg
