name: vioo_app
description: A minimal Flutter app scaffold created by the assistant
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0  # For OpenAI API calls
  speech_to_text: ^6.6.0  # For local transcription
  just_audio: ^0.9.36  # Playback for feeding audio into speech recognizer
  tflite_flutter: ^0.10.3  # Local LLM fallback inference
  flutter_dotenv: ^5.1.0  # Environment-based configuration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/local_llm.tflite
    - .env
