name: vioo_app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Fast job: quick feedback on pushes/PRs (ubuntu + stable)
  vioo_app_fast:
    name: Run vioo_app (fast)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.9.2'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.4'

      - name: Enable Flutter (pre-cache)
        run: flutter doctor -v

      - name: Cache pub packages (fast)
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/flutter/.pub-cache
          key: ${{ runner.os }}-pub-stable-${{ hashFiles('**/flutter_app/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-stable-

      - name: Cache Flutter SDK (fast)
        uses: actions/cache@v4
        with:
          path: |
            ~/flutter
            ~/.cache/flutter
          key: ${{ runner.os }}-flutter-stable
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies (fast)
        run: |
          cd flutter_app
          flutter pub get

      

      - name: Run tests (fast)
        run: |
          cd flutter_app
          flutter test

  # Full job for PRs: analysis + coverage on stable Flutter 3.19 / Dart 3.3
  vioo_app:
    name: Run vioo_app tests
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.9.2'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.4'

      - name: Enable Flutter (pre-cache)
        run: flutter doctor -v

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/flutter/.pub-cache
          key: ${{ runner.os }}-pub-stable-${{ hashFiles('**/flutter_app/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-stable-

      - name: Install dependencies
        run: |
          cd flutter_app
          flutter pub get


      - name: Static analysis
        run: |
          cd flutter_app
          flutter analyze

      - name: Run tests
        run: |
          cd flutter_app
          flutter test --coverage
      
